CREATE TABLE Question (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text varchar(2048) NOT NULL UNIQUE
);

CREATE TABLE Answer (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    answer_text varchar(2048) NOT NULL ,
    question_id int REFERENCES Question(id) ON DELETE SET NULL,
    status int
);

